### ISSUE TITLE
Project Name Suggestions

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/london-cafes-django#11]
Please submit your project name ideas :)

**Comment by LucyMac** [comment]
"Gather"

**Comment by Nandhini31** [comment]
cafes

**Comment by ghost** [comment]
CafeHack
TeamUp
Caboodle

**Comment by lili2311** [comment]
Abode
Hack Den
Focus
Vicinity

**Comment by Nandhini31** [comment]
vote for HackDen and Hackcafe

On Tue, Jun 28, 2016 at 2:07 PM, Liliana Kastilio notifications@github.com
wrote:

> Abode
> Hack Den
> Focus
> Vicinity
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/womenhackfornonprofits/london-cafes-django/issues/11#issuecomment-229043155,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJpXNAKcO1laLcZxbzhQKbLLmzMa73i2ks5qQRyMgaJpZM4IkGT5
> .

## 

_Kind  Regards,_

_Nandhini Narasimhan_
_uk.linkedin.com/in/nandhinin http://uk.linkedin.com/in/nandhinin_

**Comment by lili2311** [comment]
Huddle

**Comment by ghost** [comment]
Huddle sounds great! but there's already a huddle! :( 
https://www.huddle.com/about/

So on that that note, i've just checked others to see if it's being used or not.
- CafeHack may not work cz there's CafeHack in DK. http://cafehack.dk/ 
  HackCafe would work. 
- TeamUp won't work either.. http://teamup.org.uk/
- Caboodle won't work either.. http://www.caboodle.co.uk/
- Gather may not work... https://www.gatherhere.com/

so it looks like these are the options:
- Abode
- Hack Den
- Focus
- Vicinity
- HackCafe
- Cafes

Should we wait for more names or shall we start polling with WHFNP team?

**Comment by lili2311** [comment]
Also have to check domains and social accounts so that all are free.

**Comment by lili2311** [comment]
This is a useful tool for that: Namecheckr https://www.namecheckr.com/

**Comment by natalia-z** [comment]
from coffee & hacking combinations I came up to Hackoffee lol

I actually really like Gather. Second choice: Focus or Vicinity

2016-06-28 13:54 GMT+01:00 Afsa Akbar notifications@github.com:

**Comment by Icicleta** [comment]
Sorry for the long list, someone are not good but I added them anyway in case words can inspire with and create one more cool :)
dreamwork
teamhitting
synergy
wemeet
wework
getonboard
teamwork
collaborationisnolongerpainful
letsmakecoolstuff
meetlist
coffeelist
workplace
collaboratecomfortcoffee (ccc)
makespace
teamembrace
polished rocks
tumbling stones
outerspace
spotit
spork (spot + work) shame that finish in pork 😆 
worksafe

PS: I like long names :)
