### ISSUE TITLE
Create a Heroku app and invite the whole team

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/london-cafes-django#12]
1. Create an account on [Heroku](https://heroku.com)
2. Create a new app 
3. Invite all team members as collaborators.

Team members to invite:
- [x] Lili
- [x] Iciar
- [x] Karen
- [x] Raquel
- [x] Bibiana
- [x] Natalia
- [x] Nora
- [x] Nandhini
- [x] Lucy

**Comment by Nandhini31** [comment]
done
