### ISSUE TITLE
Create the initial Cafe model

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/london-cafes-django#29]
Create a core Cafes model
The cafes have:
1. Name
2. Description
3. Address (street, city, postcode)
4. Images list, list of image urls for the cafe
5. Ratings:
- wifi rating
- coffee rating
- atmosphere

**Comment by BibianaC** [comment]
What would be the rating options?
- very good
- good
- so so
- bad
- very bad

**Comment by lili2311** [comment]
Le't have numbers for now as it may be stars or text we don't know yet, the human readable names can be changed later anyway. Le't assume out of 5 for the moment?

**Comment by BibianaC** [comment]
Dropdown menu or check boxes?
Everything can be changed later on but if we do the things as good as possible from the beginning is time saved. To make things just to make them, it is not worth it.

**Comment by lili2311** [comment]
This ticket if only for backend implementation, front end can display the options later on as either checkbox or dropdown or stars. This should not affect the model creation? So the options can be something like

```
 RATING_OPTIONS = (
    ('NG','Not Good'),
    ('OK','OK'),


And in the model:
    rating = models.CharField(max_length=30,
        choices=RATING_OPTIONS,
        default='A') 
```

Nothing here indicates the type of front end field this will be, is this what you we asking?

Also to keep things simple we can skip the ratings for now and just have initial basic info in the model. Anything you think needs more thoughts can be a next ticket to add in later?

**Comment by BibianaC** [comment]
Thanks @lili2311
