### ISSUE TITLE
Create an initial header

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/london-cafes-django#49]
- Create initial header html and add it to the base.html template so it is present on every page 
- Wireframe: https://github.com/womenhackfornonprofits/we-meet-django/blob/master/london_cafes/london_cafes/templates/base.html
- Use `<nav>`, `<ul>`, `<li>` and `<a>` elements to describe the content of the header.
- Logo is a link to the homepage so an `href='/'`
- Create the class to style the header using bem syntax called `header` with all clases within being `header__name` example for a link within the header the class will be `header__link` You can use this as an example: https://github.com/womenhackfornonprofits/ocdaction/blob/master/ocdaction/ocdaction/templates/layout.html#L6

- Example Mobile:
![screen shot 2016-07-07 at 19 15 23](https://cloud.githubusercontent.com/assets/2911613/16664472/0771c112-4478-11e6-8504-e7f15b8d18c0.png)

Example Desktop:
![screen shot 2016-07-07 at 19 04 16](https://cloud.githubusercontent.com/assets/2911613/16664100/9815caa8-4476-11e6-8231-1e2bc673e176.png)
- Mobile first please so any media queries are for desktop only
- menu items Home, Search, About Us
- menu should be responsive
- header should have it's own sass partial file

**Comment by nuria-gs** [comment]
Hi, 
It's my first time with Django templates, so I just wanted to be sure where should I put the header code. 
I have seen that the footer is in the layout and the <header> tag  is also there, but reading the instructions:
   - should I create a new html file for the header?
   - the header block should go in the base file above the {% block layout %}?

Thanks!

**Comment by lili2311** [comment]
Hiya! Just add it where the current header tag is in the layout then it is included on every page the link above was meant to be layout not base sorry!
So yes as you mentioned here https://github.com/womenhackfornonprofits/we-meet-django/blob/master/london_cafes/london_cafes/templates/layout.html#L5

**Comment by nuria-gs** [comment]
Ok great! I was a bit confused about the instruction ;)

**Comment by lili2311** [comment]
sorry it was late haha must have been half asleep writing this

**Comment by nuria-gs** [comment]
No worries! I'm newbie, that's was also the problem haha

**Comment by nuria-gs** [comment]
I have just commited the changes, not sure if I have commited everything ok, please review ;)

**Comment by lili2311** [comment]
@nuria-gs commited them where? can you please raise a PR?
