### ISSUE TITLE
Setup an Amazon S3 bucket for use to upload images

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/london-cafes-django#58]
Create a new account on amazon S3, it is free for a year and then a few pennies a year! You can follow instructions here: http://blog.lilianakastilio.co.uk/blog/2016/01/01/Create-a-bucket-and-deploy-a-website-to-amazon-s3/

Please only pick up this ticket if you are happy to have the amazon account in your name, we can use it just for now while we are developing and when w go live switch to a different one.

**Comment by yanabar** [comment]
@lili - i will be looking into this

**Comment by lili2311** [comment]
great assigned :)

**Comment by yanabar** [comment]
I have only created the bucket - nothing to upload for now correct? 
Can I move to this one:
https://github.com/womenhackfornonprofits/we-meet-django/issues/57 ?

**Comment by lili2311** [comment]
perfect yeah, next we can create permissions that the s3 package wants but that is a separate ticket.

**Comment by yanabar** [comment]
yep - shall I close this one ?

**Comment by lili2311** [comment]
yep please 🎉

**Comment by yanabar** [comment]
hmm for some reason don't have permissions to close/assign a ticket ?!

**Comment by lili2311** [comment]
I'll add you to the team
