### ISSUE TITLE
Initial UX Research

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/london-cafes-django#9]
1. Please provide and share the initial UX research.
2. Host any documents we need on the [Shared Drive](https://drive.google.com/drive/u/0/folders/0Bw1aIZcuiBCXejBTekNLT09RZmM)

**Comment by lili2311** [comment]
Initial Questionnaire done!

**Comment by lili2311** [comment]
@afsa-a could you add the link to the questionnaire here? Are we ready to start asking the wider WHFN for participation?

**Comment by ghost** [comment]
We've only had 5 responses from our group but let's get this moving and share it publicly now. 
http://goo.gl/forms/9ixPygcfv5dxiS2N2
